const $=id=>document.getElementById(id);
let W={retention:.24,shareability:.16,originality:.15,audience_relevance:.12,spoken_hook:.11,visual_hook:.08,clarity:.05,value_emotion:.04,title:.03,rhythm:.02,cta:0};
let RULES={version:'fallback',last_verified:'',methodology:''};
const rulesReady=(async()=>{try{const r=await fetch(`meta-rules.json?v=${Date.now()}`,{cache:'no-store'});if(r.ok){RULES=await r.json();if(RULES.weights)W=RULES.weights}}catch(e){console.warn('Meta rulebook fallback',e)}})();
let currentFile=null,currentURL=null,duration=0;
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const bytes=n=>n<1048576?Math.round(n/1024)+' Ko':(n/1048576).toFixed(1)+' Mo';
function history(){try{return JSON.parse(localStorage.getItem('rs_history')||'[]')}catch{return[]}}
function saveHistory(r){const h=history();h.unshift(r);localStorage.setItem('rs_history',JSON.stringify(h.slice(0,30)));renderHistory()}
function usage(){const now=Date.now();let a=[];try{a=JSON.parse(localStorage.getItem('rs_usage')||'[]')}catch{}a=a.filter(t=>now-t<86400000);localStorage.setItem('rs_usage',JSON.stringify(a));return a}
function addUsage(){const a=usage();a.push(Date.now());localStorage.setItem('rs_usage',JSON.stringify(a));updateQuota()}
function updateQuota(){const n=usage().length;$('quota').textContent=`${Math.max(0,5-n)} analyse(s) disponible(s) sur 24 h`}
function scoreFinal(s){let x=0,total=0;for(const[k,w]of Object.entries(W)){const weight=Number(w)||0;x+=(Number(s?.[k])||0)*weight;total+=weight}return Math.round(Math.max(0,Math.min(100,total?x/total:0)))}
function color(n){return n>=75?'var(--g)':n>=55?'var(--o)':'var(--r)'}
function progress(t,n){$('status').textContent=t;$('bar').style.width=n+'%'}
$('videoInput').onchange=e=>{const f=e.target.files?.[0];$('error').textContent='';if(!f)return;if(f.size>100*1024*1024){$('error').textContent='Vidéo trop lourde : 100 Mo maximum.';e.target.value='';return}currentFile=f;if(currentURL)URL.revokeObjectURL(currentURL);currentURL=URL.createObjectURL(f);$('video').src=currentURL;$('fileName').textContent=f.name;$('fileMeta').textContent=bytes(f.size);$('preview').classList.remove('hidden');$('video').onloadedmetadata=()=>{duration=$('video').duration||0;$('fileMeta').textContent=`${bytes(f.size)} · ${Math.round(duration)} s`}};
$('analyzeBtn').onclick=async()=>{if(!currentFile)return;if(usage().length>=5){$('error').textContent='Limite de 5 analyses sur 24 h atteinte.';return}$('error').textContent='';$('loading').classList.remove('hidden');$('result').classList.add('hidden');$('analyzeBtn').disabled=true;try{await rulesReady;progress('Préparation de la vidéo…',12);const data=await analyzeWithAI(currentFile,progress);for(const k of Object.keys(W))data.scores[k]=Math.max(0,Math.min(100,Number(data.scores?.[k])||0));const report={id:Date.now().toString(36),createdAt:new Date().toISOString(),file:{name:currentFile.name,size:currentFile.size,duration},score:scoreFinal(data.scores),rulebook_version:data.rulebook_version||RULES.version,...data};saveHistory(report);addUsage();renderResult(report)}catch(e){console.error(e);$('error').textContent='Analyse impossible : '+(e?.message||e)}finally{$('loading').classList.add('hidden');$('analyzeBtn').disabled=false}};
function renderResult(r){const M=[['Rétention','retention'],['Partage / envoi','shareability'],['Originalité','originality'],['Pertinence audience','audience_relevance'],['Hook parlé','spoken_hook'],['Hook visuel','visual_hook'],['Clarté','clarity'],['Valeur / émotion','value_emotion'],['Titre','title'],['Rythme','rhythm']];const deg=Math.round(r.score*3.6);$('result').classList.remove('hidden');$('result').innerHTML=`<section class="card"><div class="score"><span class="badge">RÉFÉRENTIEL META ${esc(r.rulebook_version||RULES.version)}</span><div class="ring" style="background:conic-gradient(${color(r.score)} ${deg}deg,#29323d 0)"><b>${r.score}<small>/100</small></b></div><h3>Potentiel de recommandation</h3><p>${esc(r.verdict)}</p></div><div class="grid">${M.map(([l,k])=>`<div class="metric"><b style="color:${color(r.scores[k])}">${r.scores[k]}</b><small>${l}</small></div>`).join('')}</div><h3 class="section">Alignement Meta</h3><div class="box"><p>${esc(r.meta_alignment||'Analyse fondée sur le référentiel Meta actuel et des heuristiques ReelScore clairement séparées.')}</p></div><h3 class="section">🚨 Problème principal</h3><div class="box bad"><p>${esc(r.main_problem)}</p></div><h3 class="section">Pourquoi</h3><div class="box"><p>${esc(r.why)}</p></div><h3 class="section">Hook</h3><div class="box bad"><h4>Détecté</h4><p>${esc(r.detected_spoken_hook)}</p></div><div class="box good"><h4>Recommandé</h4><p>${esc(r.recommended_hook)}</p></div><div class="box"><h4>3 alternatives</h4>${(r.alternative_hooks||[]).map(x=>`<div class="alt">${esc(x)}</div>`).join('')}</div><h3 class="section">Titre / texte écran</h3><div class="box bad"><h4>Détecté</h4><p>${esc(r.detected_title_text)}</p></div><div class="box good"><h4>Recommandé</h4><p>${esc(r.recommended_title)}</p></div><h3 class="section">CTA · conversion</h3><div class="box"><h4>Score CTA ${Number(r.scores?.cta)||0}/100 · hors score de recommandation</h4><p>${esc(r.detected_cta)}</p></div><div class="box good"><h4>Recommandé</h4><p>${esc(r.recommended_cta)}</p></div><h3 class="section">Timeline</h3><div class="box">${(r.timeline||[]).map(e=>`<div class="event ${esc(e.status)}"><b>${esc(e.time)} · ${esc(e.label)}</b><p>${esc(e.reason)}</p></div>`).join('')}</div><h3 class="section">À corriger avant publication</h3><div class="box">${(r.action_items||[]).map((x,i)=>`<div class="alt"><b>${i+1}.</b> ${esc(x)}</div>`).join('')}</div><p class="muted">Référentiel ${esc(r.rulebook_version||RULES.version)} · vérifié ${esc(RULES.last_verified||'récemment')}. Meta ne publie pas ses poids exacts : les pondérations sont nos heuristiques, versionnées et révisées selon les sources officielles. Confiance IA : audio ${r.confidence?.audio??'?'}% · visuel ${r.confidence?.visual??'?'}% · texte ${r.confidence?.text??'?'}% · preuves Meta ${r.confidence?.meta_evidence??'?'}%.</p></section>`;$('result').scrollIntoView({behavior:'smooth',block:'start'})}
function renderHistory(){const h=history();$('history').innerHTML=h.length?h.map(r=>`<div class="historyItem"><div><b>${esc(r.file?.name||'Vidéo')}</b><br><small>${new Date(r.createdAt).toLocaleString('fr-FR')} · ${esc(r.rulebook_version||'ancienne grille')}</small></div><b style="color:${color(r.score)}">${r.score}/100</b></div>`).join(''):'<p class="muted">Aucune analyse pour le moment.</p>'}
$('clearHistory').onclick=()=>{localStorage.removeItem('rs_history');renderHistory()};
updateQuota();renderHistory();window.addEventListener('beforeunload',()=>{if(currentURL)URL.revokeObjectURL(currentURL)});