async function render(){
 if(!window.MediaRecorder||!el.canvas.captureStream)throw new Error('Rendu local indisponible sur ce navigateur.');
 const [w,h]=dims(),ctx=el.canvas.getContext('2d',{alpha:false});el.canvas.width=w;el.canvas.height=h;const mime=chooseMime();if(mime===null)throw new Error('MediaRecorder indisponible');
 progress(55,'Préparation du rendu',`${w}×${h} · ${state.cuts.length} cuts · ${state.punches.length} punch-ins`);
 const dest=await ensureAudio();if(state.gain)state.gain.gain.value=0;const stream=el.canvas.captureStream(30),tracks=[...stream.getVideoTracks()];if(dest?.stream.getAudioTracks().length)tracks.push(dest.stream.getAudioTracks()[0]);const out=new MediaStream(tracks),chunks=[],rec=new MediaRecorder(out,mime?{mimeType:mime,videoBitsPerSecond:w>=2160?18000000:8000000,audioBitsPerSecond:160000}:{videoBitsPerSecond:8000000});rec.ondataavailable=e=>{if(e.data?.size)chunks.push(e.data)};let resolveStop,rejectStop;const stopped=new Promise((res,rej)=>{resolveStop=res;rejectStop=rej});rec.onstop=resolveStop;rec.onerror=e=>rejectStop(new Error('Encodeur interrompu'));
 let raf=0,drawing=true,lastCut=false,renderErr=null;const rot=Number(el.rotation.value)||0,kept=Math.max(.1,state.duration-state.cuts.reduce((s,[a,b])=>s+b-a,0));
 const paint=()=>{if(!drawing)return;const t=el.source.currentTime||0;ctx.fillStyle='#050608';ctx.fillRect(0,0,w,h);const vis=drawVisual(ctx,w,h,t);if(!vis)drawMedia(ctx,el.source,w,h,el.framing.value,rot,activePunch(t));drawCaptions(ctx,w,h,t);raf=requestAnimationFrame(paint);};
 el.canvas.style.display='block';el.source.style.visibility='hidden';el.source.controls=false;el.result.classList.remove('show');
 try{el.source.pause();if(el.source.currentTime>.05){el.source.currentTime=0;await Promise.race([once(el.source,'seeked',5000),wait(600)]);}rec.start(750);lastCut=isCut(0);if(lastCut&&rec.state==='recording')rec.pause();paint();await el.source.play();await new Promise((resolve,reject)=>{let last=el.source.currentTime,stuckSince=performance.now();const tick=()=>{if(el.source.error){reject(new Error('Decoding failed'));return;}const t=el.source.currentTime||0,cut=isCut(t);if(cut!==lastCut){try{if(cut&&rec.state==='recording')rec.pause();if(!cut&&rec.state==='paused')rec.resume();lastCut=cut;}catch(e){reject(e);return;}}if(Math.abs(t-last)>.003){last=t;stuckSince=performance.now();}else if(performance.now()-stuckSince>5000){reject(new Error('Lecture bloquée'));return;}const removed=state.cuts.reduce((s,[a,b])=>t<=a?s:s+Math.max(0,Math.min(t,b)-a),0),outT=Math.max(0,t-removed);progress(60+(outT/kept)*33,'Montage en cours',`${fmt(outT)} / ${fmt(kept)} · lecture continue`);if(el.source.ended||t>=state.duration-.04){resolve();return;}requestAnimationFrame(tick);};tick();});}catch(e){renderErr=e;}finally{drawing=false;if(raf)cancelAnimationFrame(raf);el.source.pause();try{if(rec.state==='paused')rec.resume();}catch{}await wait(80);try{if(rec.state!=='inactive')rec.stop();}catch{}try{await Promise.race([stopped,wait(2200)]);}catch{}if(state.gain)state.gain.gain.value=1;el.source.style.visibility='visible';el.source.controls=true;el.canvas.style.display='none';state.assets.forEach(a=>{if(a.type==='video')a.el.pause();});}
 if(renderErr)throw renderErr;if(!chunks.length)throw new Error('Aucune vidéo n’a été générée.');let blob=new Blob(chunks,{type:mime||chunks[0].type||'video/mp4'});progress(95,'Validation','Contrôle du fichier final.');const normalized=await normalizeFinal(blob,w,h);blob=normalized.blob;const check=normalized.check;if(state.outputUrl)URL.revokeObjectURL(state.outputUrl);state.outputUrl=URL.createObjectURL(blob);el.output.src=state.outputUrl;el.output.load();el.outputMeta.textContent=`Demandé ${w}×${h} · fichier ${check.w}×${check.h} · ${bytes(blob.size)}`;el.download.href=state.outputUrl;el.download.download=`reel-v5-${Date.now()}.${blob.type.includes('webm')?'webm':'mp4'}`;el.result.classList.add('show');progress(100,'Reel prêt',`${check.w}×${check.h} validé · téléchargement disponible`);el.result.scrollIntoView({behavior:'smooth',block:'center'});
}

el.create.addEventListener('click',async()=>{
 if(state.rendering||!state.file)return;state.rendering=true;el.create.disabled=true;clearError();progress(1,'Démarrage','Le clic est bien reçu.');
 try{const buffer=await analyseAudio();if(el.manual.value.trim())manualWords();else await transcribe(buffer);progress(48,'Plan prêt',`${state.cuts.length} cuts · ${state.punches.length} punch-ins · ${state.words.length} mots`);await render();}
 catch(e){console.error(e);error(e.message||e);progress(0,'Rendu interrompu','Le rush original reste intact.');}
 finally{state.rendering=false;el.create.disabled=!state.file;if(state.gain)state.gain.gain.value=1;el.source.style.visibility='visible';el.source.controls=true;el.canvas.style.display='none';}
});
