function manualWords(){const text=el.manual.value.trim();if(!text)return false;const tokens=text.split(/\s+/).filter(Boolean);if(!tokens.length)return false;const kept=Math.max(.1,state.duration-state.cuts.reduce((s,[a,b])=>s+b-a,0)),step=kept/tokens.length;const sourceAt=o=>{let t=o;for(let cur=0;cur<state.duration;cur+=.05){if(!isCut(cur)){t-=.05;if(t<=0)return cur;}}return state.duration};state.words=tokens.map((t,i)=>({text:t,start:sourceAt(i*step),end:sourceAt((i+1)*step)}));el.captionStatus.textContent=`✓ ${state.words.length} mots depuis le texte manuel`;return true;}
function isCut(t){return state.cuts.some(([a,b])=>t>=a&&t<b);}
function activePunch(t){return state.punches.some(p=>Math.abs(t-p)<.55)?preset[state.preset].zoom:1;}
function dims(){const base=el.quality.value==='2160'?2160:el.quality.value==='720'?720:1080;switch(el.aspect.value){case'4:5':return[base,Math.round(base*5/4)];case'1:1':return[base,base];case'16:9':return[Math.round(base*16/9),base];default:return[base,Math.round(base*16/9)];}}
function sourceDims(media,rot){let w=media.videoWidth||media.naturalWidth||1080,h=media.videoHeight||media.naturalHeight||1920;if(Math.abs(rot)===90)[w,h]=[h,w];return[w,h];}
function drawMedia(ctx,media,w,h,fit='cover',rot=0,zoom=1){ctx.save();ctx.translate(w/2,h/2);ctx.rotate(rot*Math.PI/180);const rw=Math.abs(rot)===90?h:w,rh=Math.abs(rot)===90?w:h;const [sw,sh]=sourceDims(media,rot);const scale=(fit==='contain'?Math.min(rw/sw,rh/sh):Math.max(rw/sw,rh/sh))*zoom;const dw=sw*scale,dh=sh*scale;ctx.drawImage(media,-dw/2,-dh/2,dw,dh);ctx.restore();}
function currentWords(t){if(!state.words.length)return null;let i=state.words.findIndex(w=>t>=w.start&&t<=w.end+.08);if(i<0)return null;const rad=el.captionStyle.value==='multiline'?4:el.captionStyle.value==='monoline'?1:2;return{slice:state.words.slice(Math.max(0,i-rad),Math.min(state.words.length,i+rad+1)),active:i-Math.max(0,i-rad)};}
function drawCaptions(ctx,w,h,t){const d=currentWords(t);if(!d)return;const size=Math.max(28,w*.058),family=el.fontStyle.value==='editorial'?'Georgia,serif':el.fontStyle.value==='impact'?'Arial Black,Arial,sans-serif':'Arial,Helvetica,sans-serif';const y=el.captionPosition.value==='middle'?h*.52:el.captionPosition.value==='midlow'?h*.69:h*.79;ctx.save();ctx.font=`900 ${size}px ${family}`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.lineJoin='round';const words=d.slice.map(x=>x.text.toUpperCase());const gap=size*.25,widths=words.map(x=>ctx.measureText(x).width),total=widths.reduce((a,b)=>a+b,0)+gap*(words.length-1);let x=(w-total)/2;words.forEach((word,i)=>{const tw=widths[i],active=i===d.active;ctx.lineWidth=Math.max(4,w*.007);ctx.strokeStyle='rgba(0,0,0,.85)';if(el.captionStyle.value==='highlight'&&active){ctx.fillStyle='#ffd45a';ctx.fillRect(x-size*.08,y-size*.58,tw+size*.16,size*1.05);ctx.fillStyle='#101016';ctx.fillText(word,x+tw/2,y);}else{ctx.strokeText(word,x+tw/2,y);ctx.fillStyle=el.captionStyle.value==='karaoke'&&active?'#ffd45a':'#fff';ctx.fillText(word,x+tw/2,y);}x+=tw+gap;});ctx.restore();}
function nearestText(t){if(!state.words.length)return state.preset==='punch'?'POINT CLÉ':'À RETENIR';const i=Math.max(0,state.words.findIndex(w=>w.start>=t));return state.words.slice(i,i+5).map(w=>w.text.toUpperCase()).join(' ')||'POINT CLÉ';}
function drawGraphic(ctx,w,h,t){ctx.save();ctx.fillStyle='rgba(6,8,13,.82)';ctx.fillRect(0,0,w,h);const cw=w*.82,ch=h*.19,x=w*.09,y=h*.36;ctx.fillStyle=state.preset==='punch'?'#ff5fa7':'#151927';ctx.fillRect(x,y,cw,ch);ctx.fillStyle='#fff';ctx.font=`900 ${Math.max(26,w*.052)}px Arial`;ctx.textAlign='center';ctx.textBaseline='middle';const txt=nearestText(t);const parts=txt.split(' ');let line='',lines=[];for(const p of parts){const test=line?line+' '+p:p;if(ctx.measureText(test).width>cw*.82&&line){lines.push(line);line=p}else line=test;}if(line)lines.push(line);lines.slice(0,3).forEach((l,i)=>ctx.fillText(l,w/2,y+ch/2+(i-(lines.length-1)/2)*w*.065));ctx.restore();}
function visualAt(t){if(el.visualMode.value==='off'||state.preset==='minimal')return null;const cfg=preset[state.preset];const n=Math.floor(Math.max(0,t-1.5)/cfg.visualGap);const start=1.5+n*cfg.visualGap;if(t<start||t>start+cfg.visualLen)return null;if(state.assets.length&&el.visualMode.value!=='graphics'&&(el.visualMode.value==='footage'||n%2===0))return{type:'asset',asset:state.assets[n%state.assets.length],start};return{type:'graphic',start};}
function drawVisual(ctx,w,h,t){const v=visualAt(t);if(!v)return false;if(v.type==='graphic'){drawGraphic(ctx,w,h,t);return true;}const a=v.asset;if(a.type==='image'){drawMedia(ctx,a.el,w,h,'cover',0,1);return true;}const local=(t-v.start)%Math.max(.2,a.duration);if(Math.abs((a.el.currentTime||0)-local)>.3){try{a.el.currentTime=local}catch{}}if(a.el.paused)a.el.play().catch(()=>{});if(a.el.readyState>=2){drawMedia(ctx,a.el,w,h,'cover',0,1);return true;}return false;}
async function ensureAudio(){const Ctx=window.AudioContext||window.webkitAudioContext;if(!Ctx)return null;if(!state.audioCtx){state.audioCtx=new Ctx();state.sourceNode=state.audioCtx.createMediaElementSource(el.source);state.gain=state.audioCtx.createGain();state.sourceNode.connect(state.gain);state.gain.connect(state.audioCtx.destination);}if(state.audioCtx.state==='suspended')await state.audioCtx.resume();const dest=state.audioCtx.createMediaStreamDestination();state.sourceNode.connect(dest);return dest;}
function chooseMime(){if(!window.MediaRecorder)return null;const list=isIOS()?['video/mp4;codecs=avc1.42E01E,mp4a.40.2','video/mp4','video/webm;codecs=vp8,opus','video/webm']:['video/webm;codecs=vp9,opus','video/webm;codecs=vp8,opus','video/mp4','video/webm'];return list.find(x=>MediaRecorder.isTypeSupported(x))||'';}
async function verify(blob){const v=document.createElement('video');v.playsInline=true;v.preload='metadata';const u=URL.createObjectURL(blob);try{v.src=u;v.load();await once(v,'loadedmetadata',8000);return{ok:true,w:v.videoWidth,h:v.videoHeight,d:v.duration};}catch{return{ok:false,w:0,h:0,d:0};}finally{URL.revokeObjectURL(u);}}
async function normalizeFinal(blob,w,h){
 const check=await verify(blob);if(!check.ok)throw new Error('Le fichier généré ne peut pas être relu.');const wantsPortrait=h>w;if(!wantsPortrait||check.h>=check.w)return{blob,check};
 progress(96,'Correction portrait','Le fichier intermédiaire est paysage : correction locale H.264.');
 try{const mb=await import('https://cdn.jsdelivr.net/npm/mediabunny@1.52.0/+esm');const {Input,Output,Conversion,ALL_FORMATS,BlobSource,Mp4OutputFormat,BufferTarget,Quality}=mb;const target=new BufferTarget(),input=new Input({formats:ALL_FORMATS,source:new BlobSource(blob)}),output=new Output({format:new Mp4OutputFormat({fastStart:'in-memory'}),target});const conv=await Conversion.init({input,output,video:{width:w,height:h,fit:'fill',codec:'avc',frameRate:30,quality:new Quality('high'),allowRotationMetadata:false,allowTransformationMetadata:false,forceTranscode:true},audio:{codec:'aac',forceTranscode:true},tags:{}});if(!conv.isValid)throw new Error('Conversion portrait indisponible');conv.onProgress=p=>progress(96+p*3,'Correction portrait',Math.round(p*100)+'%');await conv.execute();if(!target.buffer?.byteLength)throw new Error('Conversion vide');const outBlob=new Blob([target.buffer],{type:'video/mp4'}),outCheck=await verify(outBlob);if(!outCheck.ok||outCheck.h<outCheck.w)throw new Error(`Sortie encore paysage ${outCheck.w}×${outCheck.h}`);return{blob:outBlob,check:outCheck};}catch(e){throw new Error('Correction portrait impossible : '+(e.message||e));}
}
