const $=id=>document.getElementById(id);const phone=$('phone'),socialLayer=$('socialLayer'),analysisLayer=$('analysisLayer'),fileInput=$('fileInput'),previewVideo=$('previewVideo'),dropzone=$('dropzone'),analyzeBtn=$('analyzeBtn'),timelineFill=$('timelineFill'),timelineText=$('timelineText'),status=$('status');const cards=[$('cardHook'),$('cardRetention'),$('cardVisual'),$('cardShare')];const copies=[...document.querySelectorAll('.storyCopy')];const badges=[...document.querySelectorAll('.socialBadge')];const mosaic=$('mosaic'),orb=$('orb'),scrollFill=$('scrollFill');let currentFile=null,currentURL=null,lastPhase=-1,ticking=false;
function setCard(i,score,note){cards[i].querySelector('strong').textContent=score;cards[i].querySelector('small').textContent=note}
function fmt(n){return n>=1000?(n/1000).toFixed(n>=10000?0:1).replace('.0','')+'K':String(n)}
function setSocialNumbers(stalled=false){const v=stalled?487:124000,l=stalled?31:18900,c=stalled?2:1800,s=stalled?0:5400,f=stalled?2:4300;$('likeCounter').textContent=fmt(l);$('commentCounter').textContent=fmt(c);$('shareCounter').textContent=fmt(s);$('sViews').textContent=fmt(v)+' vues';$('sLikes').textContent=fmt(l)+' likes';$('sFollowers').textContent='+'+fmt(f)+' followers';$('sComments').textContent=fmt(c)+' commentaires'}
function phaseFromProgress(p){return p<.22?0:p<.46?1:p<.68?2:3}
function applyScroll(){ticking=false;const rail=$('experience').getBoundingClientRect(),max=rail.height-innerHeight,p=Math.max(0,Math.min(1,-rail.top/max));scrollFill.style.height=(p*100)+'%';const phase=phaseFromProgress(p);copies.forEach((c,i)=>c.classList.toggle('active',i===phase));if(phase!==lastPhase){lastPhase=phase;if(phase===0){socialLayer.classList.add('active');analysisLayer.classList.remove('active');setSocialNumbers(false);setCard(0,'82','Compris immédiatement');setCard(1,'71','Peut être densifiée');setCard(2,'64','Ajoute une rupture');setCard(3,'79','Bon potentiel')}if(phase===1){setSocialNumbers(true);setCard(0,'41','Commence trop lentement');setCard(1,'53','Longueur au milieu');setCard(2,'38','Début trop statique');setCard(3,'49','Pas encore marquant')}if(phase===3){socialLayer.classList.remove('active');analysisLayer.classList.add('active')}}
 const sceneX=innerWidth<900?0:18-26*Math.min(1,p/.6);$('scene').style.transform=`translateX(${sceneX}vw)`;let ry=-15+18*p,rx=7-7*p,rz=-2+2*p,scale=1+.12*Math.sin(Math.min(1,p/.6)*Math.PI);if(p>.28&&p<.42){rz=90*((p-.28)/.14);ry=0;scale=1.12}if(p>.42){rz=90*(1-Math.min(1,(p-.42)/.12));scale=1.02}phone.style.transform=`translate(-50%,-50%) rotateY(${ry}deg) rotateX(${rx}deg) rotateZ(${rz}deg) scale(${scale})`;
 const m=Math.max(0,1-Math.abs(p-.43)/.13);mosaic.style.opacity=m;mosaic.style.transform=`scale(${.82+.18*m})`;const o=Math.max(0,1-Math.abs(p-.56)/.12);orb.style.opacity=o;orb.style.transform=`translate(-50%,${120-170*o}px) scale(${.6+.45*o})`;document.querySelector('.r1').style.transform=`rotate(${p*160}deg) scale(${1+.08*p})`;document.querySelector('.r2').style.transform=`rotate(${-p*110}deg) scale(${1-.06*p})`;badges.forEach((b,i)=>{const visible=phase<3?1:0;b.style.opacity=visible;b.style.transform=`translate3d(${(i%2?1:-1)*p*24}px,${(i<2?-1:1)*p*18}px,0)`});cards.forEach((c,i)=>{c.style.opacity=phase===3?1:(.3+.7*Math.max(0,1-Math.abs(p-.2)/.25));c.style.transform=`translateY(${Math.sin(p*6+i)*8}px)`})}
addEventListener('scroll',()=>{if(!ticking){ticking=true;requestAnimationFrame(applyScroll)}},{passive:true});addEventListener('resize',applyScroll);
function jumpToAnalysis(){const el=$('experience'),target=el.offsetTop+(el.offsetHeight-innerHeight)*.76;scrollTo({top:target,behavior:'smooth'})}$('navAnalyse').onclick=jumpToAnalysis;
['dragenter','dragover'].forEach(ev=>dropzone.addEventListener(ev,e=>{e.preventDefault();dropzone.classList.add('drag')}));['dragleave','drop'].forEach(ev=>dropzone.addEventListener(ev,e=>{e.preventDefault();dropzone.classList.remove('drag')}));dropzone.addEventListener('drop',e=>{const f=e.dataTransfer.files?.[0];if(f)loadFile(f)});fileInput.addEventListener('change',e=>{const f=e.target.files?.[0];if(f)loadFile(f)});
function loadFile(file){if(file.size>95*1024*1024){status.textContent='Vidéo trop lourde : 95 Mo max.';return}currentFile=file;if(currentURL)URL.revokeObjectURL(currentURL);currentURL=URL.createObjectURL(file);previewVideo.src=currentURL;dropzone.classList.add('hasVideo');previewVideo.play().catch(()=>{});timelineText.textContent=file.name;timelineFill.style.width='12%';status.textContent='Vidéo prête à être analysée';jumpToAnalysis()}
function scoreFinal(s={}){const w={retention:.24,shareability:.16,originality:.15,audience_relevance:.12,spoken_hook:.11,visual_hook:.08,clarity:.05,value_emotion:.04,title:.03,rhythm:.02};let n=0,t=0;for(const[k,v]of Object.entries(w)){n+=(Number(s[k])||0)*v;t+=v}return Math.round(n/t)}
function progress(label,p){status.textContent=label;timelineFill.style.width=p+'%';timelineText.textContent=label}
analyzeBtn.onclick=async()=>{if(!currentFile){status.textContent='Dépose d’abord une vidéo.';dropzone.animate([{transform:'scale(1)'},{transform:'scale(1.025)'},{transform:'scale(1)'}],{duration:420});return}analyzeBtn.disabled=true;analyzeBtn.textContent='Analyse…';try{const data=await window.analyzeWithAI(currentFile,progress);const s=data.scores||{};setCard(0,Math.round(((+s.spoken_hook||0)+(+s.visual_hook||0))/2),'Hook global');setCard(1,+s.retention||0,'Rétention');setCard(2,+s.visual_hook||0,'Hook visuel');setCard(3,+s.shareability||0,'Partage');const score=scoreFinal(s);timelineFill.style.width='100%';timelineText.textContent=`Score Viral+ ${score}/100`;$('mainTitle').textContent=data.main_problem||'Priorité identifiée';$('mainText').textContent=data.why||'Viral+ a terminé le diagnostic.';$('fixTitle').textContent='Hook recommandé';$('fixText').textContent=data.recommended_hook||'Une correction est prête.';status.textContent=`Analyse terminée · ${score}/100`;burstSocial(14);document.querySelector('#result').scrollIntoView({behavior:'smooth',block:'center'})}catch(e){status.textContent='Analyse impossible : '+(e?.message||e)}finally{analyzeBtn.disabled=false;analyzeBtn.textContent='Analyser la vidéo'}};
function burstSocial(count=16){const labels=['♥ +1.2K','💬 +387','↗ +96','+742 followers','12.4K vues'];const r=phone.getBoundingClientRect();for(let i=0;i<count;i++){const p=document.createElement('div');p.className='socialParticle';p.textContent=labels[Math.floor(Math.random()*labels.length)];p.style.left=(r.left+r.width/2-35+Math.random()*70)+'px';p.style.top=(r.top+r.height*.56)+'px';p.style.setProperty('--x',(Math.random()*300-150)+'px');p.style.setProperty('--y',(-150-Math.random()*240)+'px');p.style.setProperty('--r',(Math.random()*40-20)+'deg');p.style.setProperty('--dur',(1.3+Math.random())+'s');document.body.appendChild(p);setTimeout(()=>p.remove(),2400)}}phone.addEventListener('click',()=>{if(socialLayer.classList.contains('active'))burstSocial(18)});
setInterval(()=>{if(document.hidden||lastPhase!==0)return;const v=124000+Math.floor(Math.random()*1200),l=18900+Math.floor(Math.random()*180),f=4300+Math.floor(Math.random()*40);$('sViews').textContent=fmt(v)+' vues';$('sLikes').textContent=fmt(l)+' likes';$('sFollowers').textContent='+'+fmt(f)+' followers';$('likeCounter').textContent=fmt(l)},1500);addEventListener('beforeunload',()=>{if(currentURL)URL.revokeObjectURL(currentURL)});applyScroll();
