function quickAction(action){if(action==='more-dynamic')state.project.intensity=clamp(state.project.intensity+1,0,3);if(action==='simpler')state.project.intensity=clamp(state.project.intensity-1,0,3);if(action==='more-broll'){const order=['none','light','balanced','important'];const i=order.indexOf(state.project.brollLevel);state.project.brollLevel=order[Math.min(order.length-1,Math.max(0,i)+1)]}if(action==='less-effects'){state.project.intensity=Math.max(0,state.project.intensity-1);state.project.brollLevel='light'}els.editorIntensity.value=state.project.intensity;els.intensityLabel.textContent=INTENSITY_LABELS[state.project.intensity];els.editorBrollLevel.value=state.project.brollLevel;buildTimeline();saveVersion(`V${state.versions.length+1} ajustée`);}

async function loadAssets(files){for(const file of [...files].slice(0,12-state.assets.length)){const url=URL.createObjectURL(file);if(file.type.startsWith('image/')){const img=new Image();img.src=url;await once(img,'load',8000);state.assets.push({id:uid('asset'),name:file.name,type:'image',url,el:img})}else if(file.type.startsWith('video/')){const v=document.createElement('video');v.src=url;v.muted=true;v.playsInline=true;v.preload='metadata';v.load();await once(v,'loadedmetadata',10000);state.assets.push({id:uid('asset'),name:file.name,type:'video',url,el:v,duration:v.duration})}}renderAssetList();buildTimeline();track('broll_changed',{assets:state.assets.length})}
function renderAssetList(){els.assetList.innerHTML=state.assets.map((a,i)=>`<div class="assetItem"><span>${escapeHtml(a.name)}</span><button data-remove-asset="${i}" type="button">×</button></div>`).join('');qsa('[data-remove-asset]',els.assetList).forEach(b=>b.addEventListener('click',()=>{const i=Number(b.dataset.removeAsset);URL.revokeObjectURL(state.assets[i].url);state.assets.splice(i,1);renderAssetList();buildTimeline()}))}
function loadMusic(file){if(!file)return;if(state.musicUrl)URL.revokeObjectURL(state.musicUrl);state.musicUrl=URL.createObjectURL(file);const a=new Audio(state.musicUrl);a.loop=true;a.preload='metadata';a.volume=Number(els.musicVolume.value);state.music=a;toast('Musique ajoutée');buildTimeline()}
async function loadLogo(file){if(!file)return;if(file.size>1500000){toast('Logo trop lourd · 1,5 Mo max');return}const data=await fileToDataUrl(file);const img=new Image();img.src=data;await once(img,'load',6000);state.logoImage=img;state.project.brandSettings.logoData=data;toast('Logo ajouté');drawPreviewFrame(els.sourceVideo.currentTime||0)}
function fileToDataUrl(file){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(file)})}

function renderTimeline(){const tl=state.project.timeline,dur=state.source.duration;const rows=[['Vidéo','cut',tl.cuts],['Cadrage','crop',tl.crops],['B-roll','broll',tl.broll],['Textes','overlay',tl.overlays],['Sous-titres','caption',tl.captions],['Audio','audio',tl.audio],['Musique','audio',tl.music]];els.timeline.innerHTML=rows.map(([label,cls,items])=>`<div class="trackRow"><div class="trackLabel">${label}</div><div class="trackLane">${items.filter(x=>!x.deleted).map(x=>{const left=(x.start/dur)*100,width=Math.max(.4,((x.end-x.start)/dur)*100);return`<button class="eventBlock ${cls}" data-event="${x.id}" style="left:${left}%;width:${width}%" title="${escapeHtml(x.reason||x.type)}">${escapeHtml(eventLabel(x))}</button>`}).join('')}</div></div>`).join('');qsa('[data-event]',els.timeline).forEach(b=>b.addEventListener('click',()=>inspectEvent(b.dataset.event)))}
function eventLabel(e){if(e.type==='caption')return e.text;if(e.type==='broll')return e.kind==='asset'?'B-roll':'Visuel';if(e.type==='overlay')return e.text;if(e.type==='crop')return e.mode;if(e.type==='cut')return'Cut';return e.kind||e.type}
function allEvents(){const t=state.project.timeline;return Object.values(t).flat().filter(Array.isArray).flat()}
function inspectEvent(id){const ev=allEvents().find(x=>x.id===id);if(!ev)return;els.eventInspector.hidden=false;let extra='';if(ev.type==='caption')extra=`<input id="inspectorText" class="inspectorInput" value="${escapeHtml(ev.text)}">`;if(ev.type==='broll'&&state.assets.length)extra=`<select id="inspectorAsset" class="inspectorInput"><option value="-1">Visuel généré</option>${state.assets.map((a,i)=>`<option value="${i}" ${ev.assetIndex===i?'selected':''}>${escapeHtml(a.name)}</option>`).join('')}</select>`;els.eventInspector.innerHTML=`<div class="inspectorTop"><div><strong>${escapeHtml(eventLabel(ev))}</strong><div>${fmt(ev.start)} → ${fmt(ev.end)} · ${escapeHtml(ev.reason||'')}</div></div><button id="deleteEvent" type="button">Supprimer</button></div>${extra}<div class="inspectorActions"><button data-shift="-.25" type="button">← 0,25 s</button><button data-shift=".25" type="button">0,25 s →</button><button id="closeInspector" type="button">Fermer</button></div>`;$('deleteEvent').onclick=()=>{ev.deleted=true;renderTimeline();els.eventInspector.hidden=true;drawPreviewFrame(els.sourceVideo.currentTime||0)};qsa('[data-shift]',els.eventInspector).forEach(b=>b.onclick=()=>{const d=Number(b.dataset.shift),len=ev.end-ev.start;ev.start=clamp(ev.start+d,0,state.source.duration-len);ev.end=ev.start+len;renderTimeline();inspectEvent(ev.id);drawPreviewFrame(els.sourceVideo.currentTime||0)});$('closeInspector').onclick=()=>els.eventInspector.hidden=true;if($('inspectorText'))$('inspectorText').onchange=e=>{ev.text=e.target.value;ev.words=[];renderTimeline();drawPreviewFrame(els.sourceVideo.currentTime||0)};if($('inspectorAsset'))$('inspectorAsset').onchange=e=>{ev.assetIndex=Number(e.target.value);ev.kind=ev.assetIndex>=0?'asset':'graphic';renderTimeline();drawPreviewFrame(els.sourceVideo.currentTime||0)}}

function saveVersion(name,announce=true){const snapshot={name,id:uid('ver'),createdAt:Date.now(),style:state.project.style,resolvedStyle:state.project.resolvedStyle,intensity:state.project.intensity,brollLevel:state.project.brollLevel,captionSettings:deepClone(state.project.captionSettings),timeline:deepClone(state.project.timeline)};state.versions.push(snapshot);state.activeVersion=snapshot.id;renderVersions();state.project.versions=state.versions.map(({timeline,...v})=>v);saveProjectMeta();if(announce)toast(`${name} sauvegardée`)}
function renderVersions(){els.versions.innerHTML=state.versions.map(v=>`<button type="button" class="versionBtn ${v.id===state.activeVersion?'active':''}" data-version="${v.id}">${escapeHtml(v.name)}</button>`).join('');qsa('[data-version]',els.versions).forEach(b=>b.addEventListener('click',()=>restoreVersion(b.dataset.version)))}
function restoreVersion(id){const v=state.versions.find(x=>x.id===id);if(!v)return;state.project.style=v.style;state.project.resolvedStyle=v.resolvedStyle;state.project.intensity=v.intensity;state.project.brollLevel=v.brollLevel;state.project.captionSettings=deepClone(v.captionSettings);state.project.timeline=deepClone(v.timeline);state.activeVersion=id;els.styleSelect.value=v.style;els.editorIntensity.value=v.intensity;els.editorBrollLevel.value=v.brollLevel;syncCaptionControls();renderTimeline();renderVersions();updateProjectSummary();drawPreviewFrame(els.sourceVideo.currentTime||0);toast(`${v.name} restaurée`)}

function activeEvent(list,t){return list.find(e=>!e.deleted&&t>=e.start&&t<e.end)}
function drawPreviewFrame(t){const c=els.previewCanvas,ctx=c.getContext('2d');const W=c.width,H=c.height;ctx.fillStyle='#000';ctx.fillRect(0,0,W,H);const tl=state.project?.timeline;if(!state.file||!tl){return}const crop=activeEvent(tl.crops,t);const broll=activeEvent(tl.broll,t);if(broll){drawBroll(ctx,broll,W,H,t)}else{drawCover(ctx,els.sourceVideo,W,H,crop?.scale||1)}const overlay=activeEvent(tl.overlays,t);if(overlay)drawOverlay(ctx,overlay,W,H,t);const caption=activeEvent(tl.captions,t);if(caption)drawCaption(ctx,caption,W,H,t);drawBrand(ctx,W,H);}
function drawCover(ctx,media,w,h,scale=1){const vw=media.videoWidth||media.naturalWidth||1080,vh=media.videoHeight||media.naturalHeight||1920;if(!vw||!vh)return;const target=w/h,src=vw/vh;let sw,sh,sx,sy;if(src>target){sh=vh;sw=vh*target;sx=(vw-sw)/2;sy=0}else{sw=vw;sh=vw/target;sx=0;sy=(vh-sh)/2}sw/=scale;sh/=scale;sx=(vw-sw)/2;sy=(vh-sh)/2;try{ctx.drawImage(media,sx,sy,sw,sh,0,0,w,h)}catch{}}
function drawBroll(ctx,e,w,h,t){if(e.assetIndex>=0&&state.assets[e.assetIndex]){const a=state.assets[e.assetIndex];if(a.type==='video'){const local=(t-e.start)%Math.max(.2,a.duration||1);if(Math.abs(a.el.currentTime-local)>.35){try{a.el.currentTime=local}catch{}}a.el.play().catch(()=>{});if(a.el.readyState>=2)drawCover(ctx,a.el,w,h,1);else drawCover(ctx,els.sourceVideo,w,h,1)}else drawCover(ctx,a.el,w,h,1);return}ctx.save();ctx.fillStyle='#0d0f15';ctx.fillRect(0,0,w,h);const brand=state.project.brandSettings;const grad=ctx.createLinearGradient(0,h*.25,w,h*.75);grad.addColorStop(0,brand?.primary||'#8d6fff');grad.addColorStop(1,brand?.secondary||'#ff5fa7');ctx.globalAlpha=.18;ctx.fillStyle=grad;ctx.beginPath();ctx.arc(w*.78,h*.25,w*.36,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1;ctx.fillStyle='#fff';ctx.textAlign='left';ctx.textBaseline='middle';ctx.font=`800 ${w*.065}px Inter, sans-serif`;wrapText(ctx,(e.text||'POINT IMPORTANT').toUpperCase(),w*.10,h*.48,w*.78,w*.082,3);ctx.restore()}
function drawOverlay(ctx,e,w,h){ctx.save();const brand=state.project.brandSettings;ctx.fillStyle='rgba(0,0,0,.55)';roundRect(ctx,w*.09,h*.16,w*.82,h*.13,18);ctx.fill();ctx.fillStyle=brand?.secondary||'#ff5fa7';ctx.fillRect(w*.09,h*.16,w*.015,h*.13);ctx.fillStyle='#fff';ctx.textAlign='center';ctx.textBaseline='middle';ctx.font=`900 ${w*.065}px Manrope, sans-serif`;ctx.fillText(String(e.text).toUpperCase(),w*.51,h*.225,w*.7);ctx.restore()}
function drawCaption(ctx,e,w,h,t){const s=state.project.captionSettings,brand=state.project.brandSettings;if(!s)return;const font=brand?.use?brand.font:s.font;ctx.save();const progress=clamp((t-e.start)/Math.max(.08,e.end-e.start),0,1);let alpha=1,scale=1;if(s.animation==='fade')alpha=clamp(progress*5,0,1);if(s.animation==='pop')scale=progress<.18?.92+progress/.18*.08:1;ctx.globalAlpha=alpha;ctx.translate(w/2,h*s.position);ctx.scale(scale,scale);ctx.textAlign='center';ctx.textBaseline='middle';ctx.font=`${s.weight} ${s.size*(w/540)}px "${font}", Inter, sans-serif`;
  const words=e.words?.length?e.words:e.text.split(/\s+/).map((text,i)=>({text,start:e.start+i*(e.end-e.start)/Math.max(1,e.text.split(/\s+/).length),end:e.start+(i+1)*(e.end-e.start)/Math.max(1,e.text.split(/\s+/).length)}));
  let display=words;if(s.wordByWord)display=words.filter(x=>x.start<=t).slice(-1);const text=display.map(x=>x.text).join(' ').toUpperCase();const maxW=w*.84,lineH=s.size*(w/540)*1.08;const lines=splitLines(ctx,text,maxW,s.maxLines||2);const blockH=lines.length*lineH;if(s.bg){ctx.fillStyle='rgba(0,0,0,.68)';roundRect(ctx,-maxW*.54,-blockH*.68,maxW*1.08,blockH*1.35,12);ctx.fill()}
  if(s.shadow){ctx.shadowColor='rgba(0,0,0,.75)';ctx.shadowBlur=12;ctx.shadowOffsetY=4}ctx.lineJoin='round';if(s.outline){ctx.strokeStyle='rgba(0,0,0,.92)';ctx.lineWidth=Math.max(4,w*.008);lines.forEach((line,i)=>ctx.strokeText(line,0,(i-(lines.length-1)/2)*lineH,maxW))}ctx.fillStyle=s.color;lines.forEach((line,i)=>ctx.fillText(line,0,(i-(lines.length-1)/2)*lineH,maxW));
  if(s.highlight&&!s.wordByWord){const active=words.find(x=>t>=x.start&&t<=x.end+.08);if(active){ctx.shadowBlur=0;ctx.font=`${s.weight} ${s.size*(w/540)*.72}px "${font}", Inter, sans-serif`;ctx.fillStyle=brand?.use?brand.secondary:s.accent;ctx.fillText(active.text.toUpperCase(),0,blockH*.8,maxW*.7)}}ctx.restore()}
function drawBrand(ctx,w,h){const b=state.project?.brandSettings;if(!b?.use||!state.logoImage)return;const maxW=w*.18,maxH=h*.06,ratio=state.logoImage.naturalWidth/state.logoImage.naturalHeight;let dw=maxW,dh=dw/ratio;if(dh>maxH){dh=maxH;dw=dh*ratio}ctx.save();ctx.globalAlpha=.9;ctx.drawImage(state.logoImage,w-dw-w*.045,h*.045,dw,dh);ctx.restore()}
function splitLines(ctx,text,maxW,maxLines=2){const words=text.split(/\s+/),lines=[];let line='';for(const w of words){const test=line?`${line} ${w}`:w;if(ctx.measureText(test).width>maxW&&line){lines.push(line);line=w;if(lines.length===maxLines-1)continue}else line=test}if(line)lines.push(line);if(lines.length>maxLines){const rest=lines.slice(maxLines-1).join(' ');return[...lines.slice(0,maxLines-1),rest]}return lines.slice(0,maxLines)}
function wrapText(ctx,text,x,y,maxW,lineH,maxLines=3){const lines=splitLines(ctx,text,maxW,maxLines);lines.forEach((line,i)=>ctx.fillText(line,x,y+(i-(lines.length-1)/2)*lineH,maxW))}
function roundRect(ctx,x,y,w,h,r){const rr=Math.min(r,w/2,h/2);ctx.beginPath();ctx.moveTo(x+rr,y);ctx.arcTo(x+w,y,x+w,y+h,rr);ctx.arcTo(x+w,y+h,x,y+h,rr);ctx.arcTo(x,y+h,x,y,rr);ctx.arcTo(x,y,x+w,y,rr);ctx.closePath()}

async function seekSource(t){const v=els.sourceVideo;if(Math.abs(v.currentTime-t)<.04)return;v.currentTime=clamp(t,0,Math.max(0,state.source.duration-.03));await Promise.race([once(v,'seeked',2500),wait(350)]).catch(()=>{})}
function togglePreview(){if(state.preview.playing)stopPreview();else startPreview()}
async function startPreview(){if(!state.file)return;state.preview.playing=true;els.playBtn.textContent='❚❚';if(state.music){try{state.music.currentTime=els.sourceVideo.currentTime%Math.max(.1,state.music.duration||999);await state.music.play()}catch{}}try{await els.sourceVideo.play()}catch(e){state.preview.playing=false;els.playBtn.textContent='▶';toast('Touchez de nouveau pour lancer la preview');return}previewLoop()}
function stopPreview(pauseVideo=true){state.preview.playing=false;els.playBtn.textContent='▶';if(state.preview.raf)cancelAnimationFrame(state.preview.raf);state.preview.raf=0;if(pauseVideo)els.sourceVideo.pause();state.music?.pause()}
function previewLoop(){if(!state.preview.playing)return;const v=els.sourceVideo,t=v.currentTime||0;const cut=state.project.timeline.cuts.find(c=>!c.deleted&&t>=c.start&&t<c.end);if(cut&&state.preview.lastCutId!==cut.id){state.preview.lastCutId=cut.id;seekSource(cut.end+.01).then(()=>{});}else if(!cut)state.preview.lastCutId=null;drawPreviewFrame(t);syncPlayer(t);if(v.ended||t>=state.source.duration-.03){stopPreview();return}state.preview.raf=requestAnimationFrame(previewLoop)}
function syncPlayer(t){els.currentTime.textContent=fmt(t);els.scrubber.value=Math.round((t/Math.max(.01,state.source.duration))*1000)}
