async function renderProject(){
  if(state.rendering)return;state.rendering=true;stopPreview();els.renderError.hidden=true;els.renderResult.hidden=true;els.renderBtn.disabled=true;track('render_started',{quality:els.exportQuality.value});setStatus('Export en cours');
  try{
    setRenderProgress(2,'Préparation du projet','Vérification de la timeline');const quality=Number(els.exportQuality.value),w=quality,h=Math.round(quality*16/9);state.project.renderSettings={width:w,height:h,format:'mp4',videoCodec:'h264',audioCodec:'aac'};
    await ensureSourceAtZero();setRenderProgress(7,'Finalisation audio','Voix et musique');const audioDest=await buildRenderAudioGraph();
    const canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;const ctx=canvas.getContext('2d',{alpha:false});if(!canvas.captureStream)throw new Error('L’export vidéo local n’est pas disponible sur ce navigateur.');const cvs=canvas.captureStream(30),tracks=[...cvs.getVideoTracks()];if(audioDest?.stream.getAudioTracks().length)tracks.push(audioDest.stream.getAudioTracks()[0]);
    const mime=pickRecorderMime();const rec=new MediaRecorder(new MediaStream(tracks),mime?{mimeType:mime,videoBitsPerSecond:w>=1080?10_000_000:5_000_000,audioBitsPerSecond:160_000}:undefined);const chunks=[];rec.ondataavailable=e=>{if(e.data?.size)chunks.push(e.data)};const stopped=new Promise((res,rej)=>{rec.onstop=res;rec.onerror=()=>rej(new Error('L’encodeur vidéo du navigateur a interrompu le rendu.'))});
    const v=els.sourceVideo;let drawing=true,raf=0,lastCut=false;function draw(){if(!drawing)return;renderFrameTo(ctx,canvas.width,canvas.height,v.currentTime||0);raf=requestAnimationFrame(draw)}
    rec.start(800);draw();lastCut=isInsideCuts(0);if(lastCut)try{rec.pause()}catch{};if(state.music){state.music.currentTime=0;state.music.volume=Number(els.musicVolume.value);state.music.play().catch(()=>{})}await v.play();
    await new Promise((resolve,reject)=>{let last=v.currentTime,stalled=0;function tick(){if(v.error){reject(new Error('Le décodage du rush a échoué pendant l’export.'));return}const t=v.currentTime||0,cut=isInsideCuts(t),pct=12+(t/Math.max(.1,state.source.duration))*72;if(cut!==lastCut){try{if(cut&&rec.state==='recording')rec.pause();if(!cut&&rec.state==='paused')rec.resume();lastCut=cut}catch(e){reject(e);return}}if(Math.abs(t-last)<.003)stalled++;else{stalled=0;last=t}if(stalled>700){reject(new Error('La lecture du rush s’est bloquée pendant le rendu.'));return}setRenderProgress(pct,'Construction du montage',`${fmt(t)} / ${fmt(state.source.duration)} · captions, cadrages et visuels`);if(v.ended||t>=state.source.duration-.035){resolve();return}requestAnimationFrame(tick)}tick()});
    drawing=false;if(raf)cancelAnimationFrame(raf);v.pause();state.music?.pause();try{if(rec.state==='paused')rec.resume()}catch{}await wait(100);if(rec.state!=='inactive')rec.stop();await Promise.race([stopped,wait(4000)]);cleanupAudioGraph();if(!chunks.length)throw new Error('Aucun fichier vidéo n’a été produit.');
    const raw=new Blob(chunks,{type:mime||chunks[0].type||'video/webm'});setRenderProgress(87,'Encodage MP4','H.264 · AAC · portrait 9:16');const final=await finalizeMp4(raw,w,h);setRenderProgress(96,'Validation finale','Lecture du fichier sur téléphone');const meta=await verifyVideo(final);if(!meta.ok)throw new Error('Le fichier final a été créé mais ne peut pas être relu par ce navigateur.');if(meta.w&&meta.h&&meta.h<=meta.w)throw new Error(`Le fichier final n’est pas portrait (${meta.w}×${meta.h}).`);
    if(state.outputUrl)URL.revokeObjectURL(state.outputUrl);state.outputUrl=URL.createObjectURL(final);els.outputVideo.src=state.outputUrl;els.outputVideo.load();els.outputMeta.textContent=`MP4 · ${meta.w||w}×${meta.h||h} · ${fmt(meta.d||0)} · ${bytes(final.size)}`;els.downloadBtn.href=state.outputUrl;els.downloadBtn.download=`edit-reel-${Date.now()}.mp4`;els.renderResult.hidden=false;setRenderProgress(100,'Export terminé','Fichier prêt à publier');track('render_completed',{bytes:final.size,width:meta.w,height:meta.h});setStatus('Reel prêt');
  }catch(e){console.error(e);cleanupAudioGraph();friendlyError(humanizeError(e));track('render_failed',{error:String(e.message||e)});setStatus('Export interrompu')}finally{state.rendering=false;els.renderBtn.disabled=false}
}
function renderFrameTo(ctx,w,h,t){ctx.fillStyle='#000';ctx.fillRect(0,0,w,h);const tl=state.project.timeline,crop=activeEvent(tl.crops,t),broll=activeEvent(tl.broll,t);if(broll)drawBroll(ctx,broll,w,h,t);else drawCover(ctx,els.sourceVideo,w,h,crop?.scale||1);const overlay=activeEvent(tl.overlays,t);if(overlay)drawOverlay(ctx,overlay,w,h,t);const cap=activeEvent(tl.captions,t);if(cap)drawCaption(ctx,cap,w,h,t);drawBrand(ctx,w,h)}
async function ensureSourceAtZero(){const v=els.sourceVideo;v.pause();if(v.currentTime>.03){v.currentTime=0;await Promise.race([once(v,'seeked',3500),wait(450)]).catch(()=>{})}}
function pickRecorderMime(){if(!window.MediaRecorder)throw new Error('L’encodeur vidéo n’est pas disponible.');const ios=/iPhone|iPad|iPod/.test(navigator.userAgent)||(/Mac/.test(navigator.userAgent)&&navigator.maxTouchPoints>1);const list=ios?['video/webm;codecs=vp8,opus','video/webm','video/mp4']:['video/mp4','video/webm;codecs=vp9,opus','video/webm;codecs=vp8,opus','video/webm'];return list.find(x=>MediaRecorder.isTypeSupported(x))||''}
async function buildRenderAudioGraph(){const C=window.AudioContext||window.webkitAudioContext;if(!C)return null;let g=state.audioGraph;if(!g){const ctx=new C(),source=ctx.createMediaElementSource(els.sourceVideo),input=ctx.createGain(),hp=ctx.createBiquadFilter(),presence=ctx.createBiquadFilter(),comp=ctx.createDynamicsCompressor();hp.type='highpass';hp.frequency.value=70;presence.type='peaking';presence.frequency.value=3200;presence.Q.value=.8;presence.gain.value=2.2;comp.threshold.value=-20;comp.knee.value=20;comp.ratio.value=3;comp.attack.value=.008;comp.release.value=.18;source.connect(input);input.connect(hp);hp.connect(presence);presence.connect(comp);comp.connect(ctx.destination);g={ctx,source,input,hp,presence,comp};state.audioGraph=g}if(g.ctx.state==='suspended')await g.ctx.resume();const dest=g.ctx.createMediaStreamDestination();if(els.voiceEnhance.checked)g.comp.connect(dest);else g.input.connect(dest);if(state.music){if(!g.musicSource){g.musicSource=g.ctx.createMediaElementSource(state.music);g.musicGain=g.ctx.createGain();g.musicSource.connect(g.musicGain);g.musicGain.connect(g.ctx.destination)}g.musicGain.gain.value=Number(els.musicVolume.value);g.musicGain.connect(dest)}return dest}
function cleanupAudioGraph(){if(state.music)state.music.pause();const g=state.audioGraph;if(!g)return;try{g.comp.disconnect();g.comp.connect(g.ctx.destination);g.input.disconnect();g.input.connect(g.hp);if(g.musicGain){g.musicGain.disconnect();g.musicGain.connect(g.ctx.destination)}}catch{}}
async function finalizeMp4(raw,w,h){const rawMeta=await verifyVideo(raw);if(raw.type.includes('mp4')&&rawMeta.ok&&rawMeta.h>rawMeta.w&&rawMeta.w===w&&rawMeta.h===h)return raw;try{const mb=await import('https://cdn.jsdelivr.net/npm/mediabunny@1.52.0/+esm');const {Input,ALL_FORMATS,BlobSource,Output,BufferTarget,Mp4OutputFormat,Conversion,Quality}=mb;const target=new BufferTarget();const input=new Input({formats:ALL_FORMATS,source:new BlobSource(raw)});const output=new Output({format:new Mp4OutputFormat({fastStart:'in-memory'}),target});const conversion=await Conversion.init({input,output,video:{width:w,height:h,fit:'contain',codec:'avc',frameRate:30,quality:new Quality('high'),allowTransformationMetadata:false},audio:{codec:'aac',quality:new Quality('high')}});if(!conversion.isValid)throw new Error('Conversion MP4 non disponible sur cet appareil.');conversion.onProgress=p=>setRenderProgress(87+p*8,'Encodage MP4',`H.264 · AAC · ${Math.round(p*100)}%`);await conversion.execute();if(!target.buffer?.byteLength)throw new Error('Conversion MP4 vide.');return new Blob([target.buffer],{type:'video/mp4'})}catch(e){if(raw.type.includes('mp4')&&rawMeta.ok)return raw;throw new Error(`Impossible de finaliser le MP4 : ${e.message||e}`)}}
async function verifyVideo(blob){const v=document.createElement('video'),url=URL.createObjectURL(blob);v.playsInline=true;v.preload='metadata';try{v.src=url;v.load();await once(v,'loadedmetadata',8000);return{ok:true,w:v.videoWidth,h:v.videoHeight,d:v.duration}}catch{return{ok:false,w:0,h:0,d:0}}finally{URL.revokeObjectURL(url)}}

function humanizeError(e){const m=String(e?.message||e||'Erreur inconnue');if(/decode|décod/i.test(m))return'Cette vidéo utilise un encodage que le navigateur ne parvient pas à traiter correctement. Réessaie avec le même rush après l’avoir exporté en H.264/MP4 depuis Photos ou CapCut.';if(/network|réseau/i.test(m))return'Connexion interrompue. Le projet est conservé localement : réessaie quand le réseau revient.';if(/transcription/i.test(m))return'La transcription automatique n’a pas pu se charger. Le montage peut continuer, mais les captions automatiques seront limitées.';return m}
async function saveProjectMeta(){if(!state.project)return;const copy=deepClone(state.project);copy.source=state.project.source;lsSet('editplus_last_project',JSON.stringify(copy));return copy}

// Export analytics event
els.downloadBtn.addEventListener('click',()=>track('export_downloaded',{projectId:state.project?.id}));

init().catch(e=>{console.error(e);setStatus('Erreur de démarrage');toast('Impossible de démarrer l’application')});
