function buildTimeline(){
  const p=state.project,a=state.analysis,style=STYLE_PRESETS[p.resolvedStyle],intF=INTENSITY_FACTORS[p.intensity],bF=BROLL_FACTORS[p.brollLevel]*(p.brollLevel==='auto'?style.brollIntensity:1);const tl={cuts:[],captions:[],broll:[],overlays:[],crops:[],audio:[],music:[]};
  // Cleaning: remove only meaningful excess, never natural breaths.
  const silenceThreshold=clamp(.82-style.cutIntensity*.42, .34,.75);if(p.cleaning!=='off')for(const s of a.silences){const keepEdge=style.keepBreath*.22;const dur=s.duration-keepEdge*2;if(dur>=silenceThreshold)tl.cuts.push(evt('cut',s.start+keepEdge,s.end-keepEdge,{reason:'silence excessif'}))}
  if(p.cleaning==='auto'&&a.words.length){for(const f of a.fillers.slice(0,Math.ceil(4*style.cutIntensity))){if(f.end-f.start<.7)tl.cuts.push(evt('cut',Math.max(0,f.start-.03),Math.min(state.source.duration,f.end+.04),{reason:'hésitation inutile'}))}for(const r of a.repetitions.slice(0,2))tl.cuts.push(evt('cut',r.start,r.end,{reason:'répétition évidente'}))}
  if(p.hookOptimize&&a.hook?.weak&&a.hook.cutTo>.18&&a.hook.cutTo<3.5)tl.cuts.push(evt('cut',0,a.hook.cutTo,{reason:`hook optimisé · ${a.hook.reason}`}));tl.cuts=mergeCuts(tl.cuts);
  // Captions from real word timestamps.
  if(a.words.length)tl.captions=groupCaptions(a.words,p.captionSettings);
  // Semantic crop events only on meaningful moments.
  const cropNeed=style.zoomIntensity*intF;const minGap=clamp(4.2-cropNeed*2.2,1.4,4.2);let last=-99;for(const m of a.important){if(m.time-last<minGap||isInsideCuts(m.time,tl.cuts))continue;if(cropNeed<.23)continue;const strength=m.score>1.42&&cropNeed>.6?'strong-punch':m.reason==='cta'?'close-up':'punch-in';tl.crops.push(evt('crop',Math.max(.05,m.time-.12),Math.min(state.source.duration,m.time+.88),{mode:strength,scale:strength==='strong-punch'?1.15:strength==='close-up'?1.12:1.075,reason:`${m.reason||'moment fort'}`}));last=m.time}
  // Text overlays on numbers and only high-value semantics.
  const overlayMax=Math.max(1,Math.round(3*style.motionIntensity*intF));for(const o of a.overlayOpportunities.slice(0,overlayMax))if(!isInsideCuts(o.time,tl.cuts))tl.overlays.push(evt('overlay',Math.max(0,o.time-.08),Math.min(state.source.duration,o.time+1.15),{kind:o.type,text:o.text,reason:o.reason}));
  // B-roll: only semantic opportunities, never periodic.
  if(bF>0){const gap=clamp(9-6*bF,2.2,9);last=-99;const candidates=[...a.brollOpportunities,...a.important.filter(x=>x.reason==='cta').map(x=>({...x,query:'preuve / interface'}))].sort((x,y)=>x.time-y.time);for(const o of candidates){if(o.time-last<gap||isInsideCuts(o.time,tl.cuts))continue;const assetIndex=state.assets.length?(tl.broll.length%state.assets.length):-1;tl.broll.push(evt('broll',o.time,Math.min(state.source.duration,o.time+clamp(1.05+style.brollIntensity*.7,1,1.8)),{assetIndex,kind:assetIndex>=0?'asset':'graphic',text:keywordWindow(o.time),reason:o.reason||'compréhension'}));last=o.time}}
  if(els.voiceEnhance.checked)tl.audio.push(evt('audio',0,state.source.duration,{kind:'voice-enhance',reason:'clarté de la voix'}));if(state.music)tl.music.push(evt('music',0,state.source.duration,{kind:'custom',reason:'piste utilisateur'}));
  p.timeline=tl;renderTimeline();updateProjectSummary();drawPreviewFrame(els.sourceVideo.currentTime||0);return tl;
}
function evt(type,start,end,data={}){return{id:uid(type),type,start:clamp(start,0,state.source.duration),end:clamp(end,0,state.source.duration),deleted:false,...data}}
function mergeCuts(cuts){const s=cuts.filter(x=>x.end>x.start+.03).sort((a,b)=>a.start-b.start),out=[];for(const c of s){const last=out.at(-1);if(last&&c.start<=last.end+.08){last.end=Math.max(last.end,c.end);last.reason=`${last.reason} + ${c.reason}`}else out.push(c)}return out}
function isInsideCuts(t,cuts=state.project?.timeline?.cuts||[]){return cuts.some(c=>!c.deleted&&t>=c.start&&t<c.end)}
function groupCaptions(words,cfg){const out=[];let group=[];const flush=()=>{if(!group.length)return;out.push(evt('caption',group[0].start,group.at(-1).end+.05,{text:group.map(w=>w.text).join(' '),words:deepClone(group),reason:'parole'}));group=[]};for(const w of words){if(cfg.wordByWord){flush();group=[w];flush();continue}if(group.length>=cfg.words||(group.length&&w.start-group[0].start>1.65)){flush()}group.push(w)}flush();return out}
function keywordWindow(t){const w=state.analysis.words.filter(x=>x.start>=t-.15&&x.start<t+2).slice(0,7);return w.map(x=>x.text).join(' ')||'POINT IMPORTANT'}
function updateProjectSummary(){const tl=state.project.timeline;const cutDur=tl.cuts.filter(x=>!x.deleted).reduce((s,x)=>s+x.end-x.start,0);els.projectTitle.textContent=`Montage ${STYLE_PRESETS[state.project.resolvedStyle].name}`;els.projectSummary.textContent=`${tl.cuts.filter(x=>!x.deleted).length} cuts · ${tl.crops.filter(x=>!x.deleted).length} cadrages · ${tl.broll.filter(x=>!x.deleted).length} B-roll · ${fmt(Math.max(0,state.source.duration-cutDur))}`}

function enterEditor(){
  const p=state.project;p.intensity=Number(els.intensity.value);p.brollLevel=els.brollLevel.value;const sub=els.subtitlePreset.value;applyCaptionPreset(sub,false);p.style=state.selectedStyle;p.resolvedStyle=p.style==='auto'?recommendStyle(state.analysis):p.style;
  buildTimeline();els.styleSelect.value=p.style;els.editorIntensity.value=p.intensity;els.intensityLabel.textContent=INTENSITY_LABELS[p.intensity];els.editorSubtitlePreset.value=sub;els.editorBrollLevel.value=p.brollLevel;els.durationLabel.textContent=fmt(state.source.duration);els.scrubber.value=0;els.modeToggle.hidden=false;showStage('editor');drawPreviewFrame(0);saveVersion('V1 '+STYLE_PRESETS[p.resolvedStyle].name,false);track('preview_generated',{style:p.resolvedStyle});
}

function bindUI(){
  els.applyTranscriptBtn.addEventListener('click',()=>applyFallbackTranscript());
  els.styleGrid.addEventListener('click',e=>{const b=e.target.closest('.styleCard');if(b)applyStyleSelection(b.dataset.style)});
  els.generatePreviewBtn.addEventListener('click',enterEditor);els.backToUpload.addEventListener('click',()=>showStage('upload'));
  els.modeToggle.addEventListener('click',()=>{const opening=els.advancedPanel.hidden;els.advancedPanel.hidden=!opening;els.modeToggle.textContent=opening?'Mode simple':'Mode avancé'});
  els.playBtn.addEventListener('click',togglePreview);els.scrubber.addEventListener('input',async()=>{stopPreview(false);const t=state.source.duration*(Number(els.scrubber.value)/1000);await seekSource(t);drawPreviewFrame(t);syncPlayer(t)});
  els.styleSelect.addEventListener('change',()=>{state.project.style=els.styleSelect.value;state.project.resolvedStyle=state.project.style==='auto'?recommendStyle(state.analysis):state.project.style;track('preset_changed',{style:state.project.style});buildTimeline()});
  els.editorIntensity.addEventListener('input',()=>{state.project.intensity=Number(els.editorIntensity.value);els.intensityLabel.textContent=INTENSITY_LABELS[state.project.intensity];buildTimeline()});
  els.editorSubtitlePreset.addEventListener('change',()=>{applyCaptionPreset(els.editorSubtitlePreset.value);buildTimeline()});
  els.editorBrollLevel.addEventListener('change',()=>{state.project.brollLevel=els.editorBrollLevel.value;track('broll_changed',{level:state.project.brollLevel});buildTimeline()});
  qsa('.quickActions button').forEach(b=>b.addEventListener('click',()=>quickAction(b.dataset.action)));els.regenerateBtn.addEventListener('click',()=>{buildTimeline();saveVersion(`V${state.versions.length+1} ${STYLE_PRESETS[state.project.resolvedStyle].name}`);toast('Montage régénéré')});els.saveVersionBtn.addEventListener('click',()=>saveVersion(`V${state.versions.length+1} ${STYLE_PRESETS[state.project.resolvedStyle].name}`));
  qsa('.advancedTabs button').forEach(b=>b.addEventListener('click',()=>{qsa('.advancedTabs button').forEach(x=>x.classList.toggle('active',x===b));qsa('.advancedSection').forEach(x=>x.classList.toggle('active',x.dataset.panel===b.dataset.tab))}));
  const capBindings=[['captionFont','font'],['captionSize','size'],['captionWeight','weight'],['captionColor','color'],['captionAccent','accent'],['captionPosition','position'],['captionBg','bg'],['captionOutline','outline'],['captionShadow','shadow'],['captionAnimation','animation'],['captionLines','maxLines']];for(const[id,key]of capBindings){const e=els[id];e.addEventListener(e.type==='range'?'input':'change',()=>{let v=e.type==='checkbox'?e.checked:e.value;if(['size','weight','position','maxLines'].includes(key))v=Number(v);state.project.captionSettings[key]=v;track('subtitle_changed',{field:key});drawPreviewFrame(els.sourceVideo.currentTime||0)})}
  els.brollInput.addEventListener('change',e=>loadAssets(e.target.files));els.musicInput.addEventListener('change',e=>loadMusic(e.target.files?.[0]));els.musicVolume.addEventListener('input',()=>{if(state.music)state.music.volume=Number(els.musicVolume.value)});els.voiceEnhance.addEventListener('change',buildTimeline);els.logoInput.addEventListener('change',e=>loadLogo(e.target.files?.[0]));els.saveBrandBtn.addEventListener('click',saveBrand);
  els.exportBtn.addEventListener('click',()=>showStage('export'));els.backToEditor.addEventListener('click',()=>showStage('editor'));els.renderBtn.addEventListener('click',renderProject);
  qsa('.step').forEach(b=>b.addEventListener('click',()=>{if(!b.disabled){const s=b.dataset.step;showStage(s==='preview'?'editor':s)}}));
}

function applyFallbackTranscript(){const text=els.transcriptFallback.value.trim();if(!text){toast('Colle d’abord le texte parlé');return}const tokens=text.split(/\s+/).filter(Boolean),step=state.source.duration/Math.max(1,tokens.length);state.analysis.text=text;state.analysis.words=tokens.map((t,i)=>({text:t,start:i*step,end:(i+1)*step-.01}));state.project.transcript={text,language:detectLanguage(text),words:deepClone(state.analysis.words)};enrichAnalysis(state.analysis);els.transcriptFallbackBox.hidden=true;renderAnalysisSummary();const suggested=recommendStyle(state.analysis);state.project.resolvedStyle=suggested;applyStyleSelection(state.selectedStyle||'auto');toast('Transcript appliqué');}
