const cfg=window.LIAV_CONFIG||{};
const setup=document.getElementById('setup'),login=document.getElementById('login'),app=document.getElementById('app');
if(!cfg.CRM_API_URL){setup.classList.remove('hidden');throw new Error('CRM API not configured');}

const statusDefs=[['nouveau','Nouveau'],['a_qualifier','À qualifier'],['qualifie','Qualifié'],['liste_attente','Liste d’attente'],['session','Session'],['client','Client'],['perdu','Perdu']];
const problemDefs=[['direction','Je ne sais pas quoi lancer'],['execution','J’ai une idée mais je n’exécute pas assez'],['stagnation','J’ai commencé mais je stagne']];
const intentDefs=[['classplus','CLASS+'],['method','Méthode'],['coaching','Accompagnement']];
const state={leads:[],view:'pipeline',search:'',pass:sessionStorage.getItem('liav_crm_pass')||''};
const fmtDate=v=>v?new Intl.DateTimeFormat('fr-FR',{dateStyle:'short',timeStyle:'short'}).format(new Date(v)):'—';
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const tel=v=>String(v||'').replace(/\D/g,'');
const label=(defs,v)=>defs.find(x=>x[0]===v)?.[1]||v||'—';

async function api(action,extra={}){
 const res=await fetch(cfg.CRM_API_URL,{method:'POST',headers:{'Content-Type':'application/json','x-crm-pass':state.pass},body:JSON.stringify({action,...extra})});
 const json=await res.json().catch(()=>({}));
 if(!res.ok)throw new Error(json.error||'Erreur CRM');
 return json;
}

async function init(){
 if(!state.pass){login.classList.remove('hidden');return;}
 try{await api('login');showApp();}catch{sessionStorage.removeItem('liav_crm_pass');state.pass='';login.classList.remove('hidden');}
}
async function showApp(){login.classList.add('hidden');app.classList.remove('hidden');await loadLeads();}
async function loadLeads(){
 try{const json=await api('list');state.leads=json.leads||[];render();}
 catch(err){alert('Impossible de charger les leads : '+err.message);}
}
function filtered(){const q=state.search.trim().toLowerCase();if(!q)return state.leads;return state.leads.filter(l=>[l.firstname,l.whatsapp,l.email,l.problem,l.blockage_details,l.objective_90d,l.intent,l.status,l.notes].some(v=>String(v||'').toLowerCase().includes(q)));}
function render(){renderStats();renderPipeline();renderTable();document.getElementById('pipelineView').classList.toggle('hidden',state.view!=='pipeline');document.getElementById('tableView').classList.toggle('hidden',state.view==='pipeline');document.querySelector('.topbar h1').textContent=state.view==='pipeline'?'Pipeline':state.view==='followups'?'Relances':'Tous les leads';}
function renderStats(){const all=state.leads;const now=new Date();const monthStart=new Date(now.getFullYear(),now.getMonth(),1);const clients=all.filter(l=>l.status==='client').length;const qualified=all.filter(l=>['qualifie','liste_attente','session','client'].includes(l.status)).length;const month=all.filter(l=>new Date(l.created_at)>=monthStart).length;const conv=all.length?Math.round(clients/all.length*100):0;document.getElementById('stats').innerHTML=`<div class="stat"><span>Total leads</span><b>${all.length}</b></div><div class="stat"><span>Leads ce mois</span><b>${month}</b></div><div class="stat"><span>Qualifiés+</span><b>${qualified}</b></div><div class="stat"><span>Conversion client</span><b>${conv}%</b></div>`;}
function card(l){return `<article class="lead-card" draggable="true" data-id="${l.id}"><div class="name"><strong>${esc(l.firstname)}</strong><span class="score">${Number(l.score||0)}/100</span></div><div class="meta"><span>${esc(l.whatsapp||'—')}</span><span>${esc(label(problemDefs,l.problem))}</span></div>${l.intent?`<span class="intent">${esc(label(intentDefs,l.intent))}</span>`:''}${l.next_follow_up_at?`<div class="followup">Relance : ${fmtDate(l.next_follow_up_at)}</div>`:''}</article>`;}
function renderPipeline(){const data=filtered();document.getElementById('pipelineView').innerHTML=statusDefs.map(([key,labelTxt])=>{const list=data.filter(l=>l.status===key);return `<section class="column" data-status="${key}"><div class="column-head"><b>${labelTxt}</b><span>${list.length}</span></div><div class="cards">${list.map(card).join('')}</div></section>`}).join('');bindCards();bindDrop();}
function renderTable(){let data=filtered();if(state.view==='followups'){const limit=new Date(Date.now()+7*86400000);data=data.filter(l=>l.next_follow_up_at&&new Date(l.next_follow_up_at)<=limit).sort((a,b)=>new Date(a.next_follow_up_at)-new Date(b.next_follow_up_at));}
document.getElementById('tableView').innerHTML=`<table><thead><tr><th>Lead</th><th>WhatsApp</th><th>Intention</th><th>Statut</th><th>Score</th><th>Entrée</th><th>Relance</th></tr></thead><tbody>${data.map(l=>`<tr data-id="${l.id}"><td><b>${esc(l.firstname)}</b><br><span>${esc(l.email||'')}</span></td><td>${esc(l.whatsapp||'—')}</td><td>${esc(label(intentDefs,l.intent))}</td><td>${esc(label(statusDefs,l.status))}</td><td>${Number(l.score||0)}</td><td>${fmtDate(l.created_at)}</td><td>${fmtDate(l.next_follow_up_at)}</td></tr>`).join('')}</tbody></table>`;document.querySelectorAll('tr[data-id]').forEach(r=>r.addEventListener('click',()=>openDrawer(r.dataset.id)));}
function bindCards(){document.querySelectorAll('.lead-card').forEach(c=>{c.addEventListener('click',()=>openDrawer(c.dataset.id));c.addEventListener('dragstart',e=>{c.classList.add('dragging');e.dataTransfer.setData('text/plain',c.dataset.id)});c.addEventListener('dragend',()=>c.classList.remove('dragging'));});}
function bindDrop(){document.querySelectorAll('.column').forEach(col=>{col.addEventListener('dragover',e=>{e.preventDefault();col.classList.add('drop')});col.addEventListener('dragleave',()=>col.classList.remove('drop'));col.addEventListener('drop',async e=>{e.preventDefault();col.classList.remove('drop');const id=e.dataTransfer.getData('text/plain');await updateLead(id,{status:col.dataset.status});});});}
async function updateLead(id,patch){try{const json=await api('update',{id,patch});const i=state.leads.findIndex(l=>l.id===id);if(i>=0)state.leads[i]=json.lead;render();return true;}catch(err){alert(err.message);return false;}}
function optionList(defs,current){return defs.map(([v,n])=>`<option value="${v}" ${current===v?'selected':''}>${n}</option>`).join('');}
function openDrawer(id){const l=state.leads.find(x=>x.id===id);if(!l)return;const d=document.getElementById('drawer');document.getElementById('drawerContent').innerHTML=`<p class="eyebrow">FICHE LEAD</p><h2>${esc(l.firstname)}</h2><p class="sub">Entré le ${fmtDate(l.created_at)} • Source : ${esc(l.source||'—')}</p><div class="fields"><div class="field"><label>Prénom</label><input id="f_name" value="${esc(l.firstname)}"></div><div class="field"><label>Âge</label><input id="f_age" type="number" min="13" max="100" value="${esc(l.age??'')}"></div><div class="field"><label>WhatsApp</label><input id="f_whatsapp" value="${esc(l.whatsapp||'')}"></div><div class="field"><label>Email</label><input id="f_email" type="email" value="${esc(l.email||'')}"></div><div class="field"><label>Statut</label><select id="f_status">${optionList(statusDefs,l.status)}</select></div><div class="field"><label>Score /100</label><input id="f_score" type="number" min="0" max="100" value="${Number(l.score||0)}"></div><div class="field full"><label>Situation</label><textarea id="f_situation">${esc(l.situation||'')}</textarea></div><div class="field full"><label>Blocage principal</label><select id="f_problem">${optionList(problemDefs,l.problem)}</select></div><div class="field full"><label>Détail du blocage</label><textarea id="f_blockage">${esc(l.blockage_details||'')}</textarea></div><div class="field full"><label>Objectif 90 jours</label><textarea id="f_goal">${esc(l.objective_90d||'')}</textarea></div><div class="field"><label>Intention</label><select id="f_intent">${optionList(intentDefs,l.intent)}</select></div><div class="field"><label>Prochaine relance</label><input id="f_follow" type="datetime-local" value="${l.next_follow_up_at?new Date(new Date(l.next_follow_up_at).getTime()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16):''}"></div><div class="field full"><label>Notes</label><textarea id="f_notes">${esc(l.notes||'')}</textarea></div></div><div class="drawer-actions"><button id="saveLead" class="primary">Enregistrer</button><a class="whatsapp" target="_blank" rel="noopener" href="https://wa.me/${tel(l.whatsapp)}">Ouvrir WhatsApp ↗</a><button id="deleteLead" class="danger">Supprimer</button></div>`;
d.classList.remove('hidden');d.setAttribute('aria-hidden','false');
document.getElementById('saveLead').onclick=async()=>{const patch={firstname:document.getElementById('f_name').value.trim(),age:document.getElementById('f_age').value?Number(document.getElementById('f_age').value):null,whatsapp:document.getElementById('f_whatsapp').value.trim(),email:document.getElementById('f_email').value.trim()||null,status:document.getElementById('f_status').value,score:Number(document.getElementById('f_score').value||0),situation:document.getElementById('f_situation').value.trim()||null,problem:document.getElementById('f_problem').value,blockage_details:document.getElementById('f_blockage').value.trim()||null,objective_90d:document.getElementById('f_goal').value.trim()||null,intent:document.getElementById('f_intent').value,next_follow_up_at:document.getElementById('f_follow').value?new Date(document.getElementById('f_follow').value).toISOString():null,notes:document.getElementById('f_notes').value.trim()||null};if(await updateLead(id,patch))closeDrawer();};
document.getElementById('deleteLead').onclick=async()=>{if(!confirm('Supprimer définitivement ce lead ?'))return;try{await api('delete',{id});state.leads=state.leads.filter(x=>x.id!==id);closeDrawer();render();}catch(err){alert(err.message);}};}
function closeDrawer(){const d=document.getElementById('drawer');d.classList.add('hidden');d.setAttribute('aria-hidden','true');}
document.querySelectorAll('[data-close-drawer]').forEach(el=>el.addEventListener('click',closeDrawer));document.addEventListener('keydown',e=>{if(e.key==='Escape')closeDrawer();});
document.getElementById('loginForm').addEventListener('submit',async e=>{e.preventDefault();const input=document.getElementById('loginPassword');state.pass=input.value;const err=document.getElementById('loginError');err.textContent='';try{await api('login');sessionStorage.setItem('liav_crm_pass',state.pass);await showApp();}catch(ex){state.pass='';err.textContent='Code d’accès incorrect.';}});
document.getElementById('logoutBtn').addEventListener('click',()=>{sessionStorage.removeItem('liav_crm_pass');state.pass='';app.classList.add('hidden');login.classList.remove('hidden');document.getElementById('loginPassword').value='';});
document.getElementById('refreshBtn').addEventListener('click',loadLeads);document.getElementById('searchInput').addEventListener('input',e=>{state.search=e.target.value;render();});document.querySelectorAll('.nav-btn').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.nav-btn').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.view=b.dataset.view;render();}));
init();
